language: swift
os: osx
osx_image: xcode15.4

branches:
  only:
    - main

before_install:
  - gem install cocoapods # 安装 CocoaPods
  - pod install # 安装项目的 Pod 依赖

script:
  - xcodebuild -workspace LuckyCache.xcworkspace -scheme LuckyCache -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=13.0' clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO